name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: List files
      run: ls -R

    - name: Compile and run tests
      run: |
        cd $GITHUB_WORKSPACE
        javac Task1.java Task1Test.java
        java -cp . Task1Test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.xml 
